---
images:
  - 'gcr.io/comparison-site-client-2/comparison-site-client-3:$COMMIT_SHA'
steps:
  - args:
      - build
      - '-t'
      - 'gcr.io/comparison-site-client-2/comparison-site-client-3:$COMMIT_SHA'
      - '.'
    name: gcr.io/cloud-builders/docker
  - args:
      - push
      - 'gcr.io/comparison-site-client-2/comparison-site-client-3:$COMMIT_SHA'
    name: gcr.io/cloud-builders/docker
  - args:
      - run
      - deploy
      - comparison-site-client-3
      - '--image'
      - 'gcr.io/comparison-site-client-2/comparison-site-client-3:$COMMIT_SHA'
      - '--region'
      - us-central1
      - '--platform'
      - managed
    name: gcr.io/cloud-builders/gcloud
