steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/comparison-site-client-2/comparison-site-client-2:${SHORT_SHA}',
        '.',
      ]
    # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/comparison-site-client-2/comparison-site-client-2']
    # deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'comparison-site-client-2',
        '--image',
        'gcr.io/comparison-site-client-2/comparison-site-client-2:${SHORT_SHA}',
        '--region',
        'us-central1',
        '--allow-unauthenticated',
      ]
    env:
      - 'PORT=8080'
images:
  - gcr.io/comparison-site-client-2/comparison-site-client-2
